# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-MP4Stream
version:      0.01_01
version_from: lib/Crypt/MP4Stream.pm
installdirs:  site
requires:
    Crypt::Rijndael:               0
    Digest::MD5:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
